### ISSUE TITLE
Countermeasures

### ISSUE THREAD

**Issue by Bubbus** [Bubbus/ACF-Missiles#12]
Add countermeasures.  Anything is good if it meets gameplay standards:
Effect must be obvious.
Effect must be visible.
Effect must be effective.
Effect must be counterable (circumvention...).

Let's chat about this here for the record and start working on them first thing after initial release (we've got a lot left to do as it stands).

**Comment by Cre8or** [comment]
Quick recap of the ideas I had for countermeasures:

Flares. Used to stop radar-guided missiles (technically unrealistic but radar is really just heat seeking).
Flare dispensers exist in various shapes, here are two main types that I think we should consider:
http://www.kb9ukd.com/camera/2001/010520_440th_afd/slides/JollyBlack_flare-pods.jpg
http://www.cobham.com/media/849303/flare_dispenser_499x198.jpg

The visual effect would be similar to the rocket trail, with an added bright glow on the projectile. Sounds are already implemented in ACF, meaning this shouldn't be a lot of work.

Effectiveness: when a radar missile tracks a target, it needs to include flares in its find events. Depending on the missile type, every flare has a chance of becoming the new target, with weaker short-range missiles being more prone to flares than long-range ones. The missile marks every flare it has tested as "checked", meaning they will be filtered out from any further scans, helping with performance.

Functionality: Flare dispensers should be full-automatic, high ROF and single-magazine - meaning once all flares have been used, it needs to reload (allow rearming from ammo crates?).
Projectile length determines burn time, propellant determines muzzle velocity.

**Comment by ColBeckett** [comment]
i agree about that
that first link you provide is nice for me so i think it should looks like that

i can do that model but first i have to finish bombs (at least FABs) and that rack (but i think i will finish it today)

**Comment by Bubbus** [comment]
Sounds good.  Just speculation here, but to reduce the workload I think we can actually implement the flare launchers as an ACF gun with a new flare ammo-type.  It'd end up working like a rapid-fire smoke launcher, but with more flare.

**Comment by ColBeckett** [comment]
we should do same thing with smoke launchers (smoke ammo) vs ATGM missiles - when ATGM missile tracks a target it needs to include smoke in its events

i think BF2 way should be nice enough:https://www.youtube.com/watch?v=QQKxPvnuhI4 2:30 - cant find better video in short time:P

**Comment by Cre8or** [comment]
Iirc Bubbus and I discussed this before, and we concluded that this would at best be a low-priority task. The reason for this is that right now the missiles are by far the most complex weapons in the lot, so adding more to them at this point would really overcomplicate it (and also delay the beta a fair bit).

**Comment by ColBeckett** [comment]
i made some research about countermeasures and i think i have 2 types of flare-pods:

first one Jolly-Black you mentioned - it should be very light but will have only limited amount of flares
another one - big C-160 flare pod - able to deploy 3 times more flares in one time (usefull in bombers/cargo planes) http://upload.wikimedia.org/wikipedia/commons/a/a5/C-160_Chaffs-flares_Pod.jpg

also with smoke and flare countermeasures how about to include "Iron Curtain" - that should works only vs air to ground/ ground to ground missiles - but thats only idea for now

**Comment by Cre8or** [comment]
Here's what we'll be using:
http://www.kanfit.com/JPG/Pictures%20catalog%20page/mag4.jpg
http://balkannovoteh.co.rs/en/wp-content/uploads/products/AV26_2.png

Both do the exact same thing and work in the same way. Also, they should be parentable, just like the smoke launchers. If people want to build big cargo planes, they can just parent a bunch of these to it.

We won't be doing any other counter-measures for the time being.

**Comment by ColBeckett** [comment]
i already made that first model from my post
but ye we can use one of those you provided

**Comment by Bubbus** [comment]
From the XCF rack issue:

> Cre8or commented 15 hours ago
> - Could we perhaps set some launchers to behave more like guns in that regard? I'm thinking flare pods won't need to have any models spawned in them, as they can easily carry up to 20-30 flares per unit. We'll need a different system for them.
> 
> ColBeckett commented 15 hours ago
> - or just use acf gun system and make it like smoke launcher
> 
> Cre8or commented 13 hours ago
> - Thing is, flare pods should work without ammo crates, much like the FFAR pods do. With the difference being that it doesn't spawn any flare entities until they're required (when firing). I'm not sure how difficult this would be to implement, as I can't think of any ACF gun that has this behaviour (more than 1 round loaded inside the gun).
> 
> Bubbus commented 4 hours ago
> - Autocannons, HMGs etc have magazines, I'm hoping we can make an "autocannon flare launcher" and then somehow trick it into launching flare effects instead of bullet effects.

**Comment by Dale1994** [comment]
I would also like to see some sort of way to filter out aircraft from tanks, to keep AA missiles from locking on to them. Perhaps a trace that goes straight down that ignores the contraption?

**Comment by Bubbus** [comment]
Differentiating ground vehicles from air vehicles isn't a 100% solvable problem, it only has heuristic answers.  If we use a trace, it could just be a low-flying jet or a parked chopper.  If we look for wheels, what defines a wheel?  Also, maybe it's a hovercraft or a propeller-pushed car?

Tanks will be able to carry countermeasures too of course.  It could be fun!

**Comment by ted234521** [comment]
If the only countermeasure is going to be flares, then why do missile currently have different guidance types (laser, radar, etc)? In reality, as I'm sure you know, radar guided missiles are fooled by chaff, heat seekers by flares, laser by smoke, etc. etc. Are differences in guidance behaviors planned, or are they different in name only?

**Comment by Bubbus** [comment]
They're pretty different, you see radar on the more agile missiles like stingers - it takes an entity input or makes its own, and can be flared out.  Laser guidance is on the top-range anti tank missiles and takes a position or entity input - it has a view-cone for guidance and can be flared out.  Finally you'll get wire guidance on the lower-end anti-tank missiles - generally the least agile but takes any input, has a max guidance range and can't be flared out.
I might remove the entity input for wire guidance because the rationale there is that you can defend against LOS guidance by popping smoke, naturally obscuring the view.

Open to ideas on different _forms_ of countermeasure, but I don't want to make a distinction between flares and chaff because ACF already has a complexity issue.  Let's just call them combination IR/radio flares and be done with it?

**Comment by ted234521** [comment]
Ah, makes sense. I apologize for my apparent lack of knowledge on the subject, I haven't really tested the missile too extensively so I didn't realize. Combination flares sounds good, I totally agree on the whole issue of complexity.

**Comment by Cre8or** [comment]
To help clear things up:

AAMs and SAMs are the only missile types in our pack that (should) use entity-based radar guidance. ASMs on the other hand use laser and wire-based guidance, which both require a position vector input.

While in reality, some of the AAMs and SAMs use heat-seeking guidance, we decided to combine everything in one big bundle and call it "radar guidance", for the sake of simplicity - even if this isn't realistically accurate. The reason we did this is because we realised we would otherwise need two types of countermeasures: flares (for heat-seeking) and chaff (for radar). From a technical point of view, however, both types of countermeasures and guidance systems would behave exactly the same, except for the visual effects.

We then took the radar/chaff-combo out of the equation, however, we kept the guidance name of it ("radar"), in hopes that more people would understand what that meant. Although technically, it would have to be "infrared homing".

I could go on about the specifics of laser and wire guidance, as there's still a bit of confusion on what the difference between the two is, but I'd much rather write that down in the wiki than here.
(EDIT: [done](https://github.com/Bubbus/ACF-Missiles/wiki/Library:-Guidance))

**Comment by ted234521** [comment]
Carrying over my comments from facepunch, why not just have ACF "break" certain features of E2 when installed? Only ones relevant to ACF of course, like disabling E2s from recognizing missile entities and such. I can't really think of a way to force radar entity use, but that would at least allow for a balanced warning system. Countermeasures of course would be completely fine, as E2 has no way of impacting missile performance. Perhaps a radar ent should be implemented anyway, since servers like GGG disable certain bits of E2 needed for a radar and it would be nice to have the option there. Like it was said earlier, it's up to the server owners to enforce certain things. If some servers want radars and other want OP E2 shit, then that's their choice.

**Comment by Cre8or** [comment]
This is a tricky, and probably unnecessarily complex thing to do, because it involves hacking into Wiremod's files to blacklist the missiles from being found. This would be difficult to maintain as Wiremod is updated on a weekly, if not daily basis. Also, there are more ways of finding entities, including the beacon sensor - if we were to "break" E2 functions, there would always be a bypass.

Like Bubbus mentionned before, we can't please everyone as we're an open mod for a broad community. Unfortunately, this is a suggestion where we think the benefit would be too unsignificant over the amount of work we'd put into it.

**Comment by Mecaguy03** [comment]
I think that it would be possible to make a simple flare system that should work until its more fleshed out. Pretty much when the missile fires and it sorts through targets in its sensor cone, if it could preferentially target flare entities over everything else, then you just need a flare dispenser. As I understand it, the missile only does this target finding once on launch because it is expensive to do, so flares deployed after a missile launch would be ineffective. 

With a setup such as this planes can still cover themselves during ground strafing and sometimes during dogfights by dumping flares in anticipation of getting shot at by missiles, but if the flare dispensers have a limited number of shots then they cant just dump flares all the time.

This would pretty much mean that aircraft can only avoid missiles for a time, but once the flares dissapear or it runs out of them, it will be vulnerable to missiles, so the circumvention would be to wait until the flares are gone or to fire before the aircraft deploys flares, or until it moves away from the flares.

I think the flare dispenser should dispense one flare at a time, and it should be relatively lightweight and you should be able to parent it. IRL flares are quite easy to mount, and so they should be in ACF.

**Comment by Bubbus** [comment]
I'm waiting for effects and models before I continue, I don't want to be the only one working on this.

**Comment by Bubbus** [comment]
Flares are done.  I'd rather have more focused discussions so if we have any other ideas then let's create a thread for each of them.
