### ISSUE TITLE
missile/bomb weight

### ISSUE THREAD

**Issue by ColBeckett** [Bubbus/ACF-Missiles#32]
We should add prop weight of missile/bomb
info should be taken from missile_bomb.lua or missile_asm.lua etc.

example: 500kg bomb should have weight 500kg, hellfire missile 45kg etc.

another idea to changeable rack weight:
example - i spawn 1rk rack and it weight 100kg, if i put 500kg bomb on it - rack weight change to lets say1000kg etc.
that may cause problems in contraptions but in other way ppl will understand this and that should also works

it may be usefull in future ballance (now 500kg bomb can rekt 60t tank in 2 splash hits (5meters from tank)

**Comment by Bubbus** [comment]
That brings up a good point.  Missiles have weight applied by the 'shell length' etc, but this is usually really low.  Because missiles are parented, their mass doesn't affect the rack's momentum etc.  If the missile has its mass removed when it's on the rack, we can put the weight on the rack instead to make it more challenging to build with.

The problem with making a constant mass is that it removes one of the incentives to make lower-powered weapons.  The ammo-crate will also need to be hacked up so it doesn't weigh a tiny amount - if we didn't do this then a plane might fall from the sky just by loading the bombs onto the racks.

This is a lot of effort.  I vote post-beta.

**Comment by Cre8or** [comment]
Doesn't sound like an important issue to me. From what I understand racks/pods work like regular weapons, which change their weight in accordance to the loaded ammunition. If this is about adjusting the weights so that they use realistic values, rather than approximations based on round dimensions, then I too think this should be post-beta

**Comment by ColBeckett** [comment]
well it is - cause now you can put 20x 500kg bomb on 2t plane with no consequences - it will still fly etc.
now no matter what bomb you set - it will always weight 10kg

**Comment by Bubbus** [comment]
Partially added in 19c3ab5493640a9be82e1697b8128b1832a9b82f along with some other good stuff.  Still have to adjust ammo-crate mass, but that can happen post-beta.

**Comment by ColBeckett** [comment]
Yesterday i tested 500kg bombs on very light plane and that works - plane wobbling all the time and were really heavy
we can close that for now i think
