### ISSUE TITLE
StA Nerf.

### ISSUE THREAD

**Issue by Dale1994** [Bubbus/ACF-Missiles#48]
The pen on the missiles was pretty much halved. I think we should give them a slight buff back, not to what is was before but some where in between, to account for HEAT mechanics. They ammo count got insanely buffed when HEAT got nerfed. I think lower ammo count longer reloads but higher penetration would be a better idea.

**Comment by Cre8or** [comment]
The issue with pen is that ACF is by no means realistic when it comes to penetration. The average tank has a front armour of ~150mm, whereas most MBTs these days have a RHAe of ~600mm or more. We had to adapt the missiles' penetration and HE energy from the very beginning on to compensate for those low armour values.

Take the AGM-114 as an example. Before my last balancing commit, they had a max penetration of ~800mm, allowing them to destroy just about any tank in one hit. The result is that a lot of people would add AGM racks to their tanks, having realised that they're more effective than every equivalent ACF gun/cannon. I still feel that they're very powerful despite that nerf, as missiles are more versatile than ordinary projectiles and don't necessarily approach their target horizontally, unlike most other projectiles.

Because of this, I'm not considering any more balancing at the time until we get more feedback on the current situation. Or until ACF changes something that the missiles depend on.

**Comment by Bubbus** [comment]
HEAT buff occurred in 782f4b7ee0bb634f5f17095a8562f92bb7f7db5d.
