### ISSUE TITLE
From FP #1:  Radar hit rates

### ISSUE THREAD

**Issue by Bubbus** [Bubbus/ACF-Missiles#49]
Kardel posted:

Thanks great, another issue tho, Is it normal that Radar guidance misses 90% of times?
Ive testing on both static and moving targets and it seems to allways miss, especially when too close or too far. Ive also found contraptions moving fast (not meaning SANICFAST, but you get it, like 80km/h) missing by so much. Any way it can be improved?

And yes, Im posting this here because I dont have any other ways of contacting you.

**Comment by Cre8or** [comment]
It is true that the guidance code of the missiles has trouble with fast-moving targets (~60 km/h and up), which comes down to how it calculates the point of impact. There is no real fix for this other than finding a completely different method of calculating the trajectory altogether.

Here's a bit of insight on what happens in the two scenarios you mentionned:
- When a target is very close, the missile will have little time to build up speed, which is necessary to steer. If it's too slow, it can't turn quickly enough to hit the target and will miss.
- When the target is too far on the other hand, the missile will have ran out of propellant and will use its remaining speed to keep itself moving towards the target. It will essentially glide through the air with its nose facing upward, but will lose a lot of speed in the process. If this gliding phase lasts for too long, the missile will be too slow to maneuver, and will start falling until it detonates on impact.

This is true for both moving and static targets, as they're the two "extremes" of the spectrum. Inbetween them, however, is a wide span of chances for your missile to reliably hit its target. Try hitting a static target at 200-300 meters on full propellant, and you should be able to reliably hit with every guided missile type.

Keep in mind that some missiles are best suited for long-range static targets (mostly SAMs), while others are designed for short-range fast-moving targets (AAMs). No missile is really suited for all scenarios, which is why you have to pick the right type for your requirements.

**Comment by Bubbus** [comment]
Nice, added to https://github.com/Bubbus/ACF-Missiles/wiki/Questions---Answers.  Going to put this somewhere prominent.
