### ISSUE TITLE
From FP #2:  Missile positioning lag + ATGM buff

### ISSUE THREAD

**Issue by Bubbus** [Bubbus/ACF-Missiles#50]
mecaguy03 posted:

Also if the ACF missile devs do read this thread, ACF missiles at the moment cause strain on the server when they reload, and if they reload while moving at speed the missiles are not parented in the right position on the launcher. Specifically this has happened with the 4x ATGM racks.

Also the range on the ATGMs should be buffed in my opinion.

**Comment by Dale1994** [comment]
I agree with the range buff. I would also agree for an overall buff to all missiles once counter measures are added.

**Comment by Cre8or** [comment]
The parenting issue has been around for quite some time, though I'm not sure how we could tackle it. For the sake of comparison, E2's propcore extension is known to have the same issue with using setPos() and parentTo() in the same tick, so this isn't a new topic.

As for the reloading lag, I'm not sure what this could be caused by. Other than spawning a missile entity on a rack and parenting it, I don't see any code that could cause unreasonably high amounts of strain.

Lastly, the AGM-114 is designed to be more effective than the BGM-71E, but at the expense of agility. Range isn't much of an issue, as it's meant to be fired from aircraft. If you can't get enough range out of them, fly higher - these missiles cannot approach their target horizontally, and instead require altitude to glide towards the target.

**Comment by Bubbus** [comment]
Good answers, added to https://github.com/Bubbus/ACF-Missiles/wiki/Questions---Answers.

Going to take a look at the parenting thing **again**, so keeping this open for now.

**Comment by Bubbus** [comment]
Parenting issue seems better in 351e6f7c0bc3f8129ac9a0e5ed69b42f34ce557b.  Will roll out this patch later in the week.  Re-open if issue persists.

Closing old balance issues due to subsequent changes.  Re-open if you feel the issue persists.
