### ISSUE TITLE
Missile Parenting

### ISSUE THREAD

**Issue by Mecaguy03** [Bubbus/ACF-Missiles#53]
I think that missile racks should be able to be parented to wire chips. The potential for abuse is pretty low and it will help with mounting them as secondaries on many different things. It will also decrease lag for contraptions that use them as there will be less physical objects.

**Comment by Bubbus** [comment]
At first I didn't make them parentable because they're essentially big guns, and big guns are also unparentable.  What I found later is that it makes them more challenging to mount on vehicles.  They change weight when they're loaded, so air vehicles get lop-sided if they fire from one wing and not the other.  It also adds real considerations to placement on the vehicle, if you put a launcher on the aircraft's nose then you become nose heavy.

Making them parentable would remove some of the inconvenience which I think actually balances missiles a lot versus guns.  Maybe you disagree, I'm open to opinions.

**Comment by Cre8or** [comment]
This won't be a big issue if the difference in mass between a fully loaded rack/pod is small - which it should be, as our missiles have realistic masses. The centre of mass issue with firing on one side and not the other can be avoided by equipping missiles in a symmetrical manner, and alternating between them when firing.

Building aircraft requires more effort than land vehicles due to the mass repartition, which is a side-effect of them not having any ground contact. I personally enjoy having to put more thought into them so as to design them efficiently, rather than just slapping a dozen or so rocket pods under a pylon and expecting that to work. You can still achieve that, however, by either using a lot of applyAngForce stabilisation, or by increasing the aircraft's mass itself.

**Comment by Mecaguy03** [comment]
I suppose so, although in the process of balancing you should take care to not have racks weigh too much. On most standard acf rule sets the limit for non-acf powered aircraft is 10 tons, which can limit your practical base plate weights significantly. Non-acf power (E2) is one of the most practical ways of making an aircraft, so it should be taken into consideration when balancing weights.

**Comment by Bubbus** [comment]
It's difficult because people use the same racks on tanks too.  Since we buffed the reload rate of multi-racks, a tank with two hellfire racks can lay down a devastating salvo with a nice reload speed...  Can't give them that for too cheap a weight cost, in my opinion at least.

**Comment by Cre8or** [comment]
I would allow for that, personally. Not because I support tanks with missiles, but because this is why servers usually have ACF rules. Like I've said before, it is not our job to make sure people don't abuse missiles, because if they wanted to they'd always find a way. That's up to server admins to handle.

**Comment by Dale1994** [comment]
Mass would be the same even with parenting. So parenting shouldn't be an issue.

**Comment by Cre8or** [comment]
That's missing the point. By parenting the racks, you bypass the whole centre-of-mass problem altogether, and we don't approve of that.

**Comment by Bubbus** [comment]
thread is dead
