### ISSUE TITLE
Rack durability

### ISSUE THREAD

**Issue by Mecaguy03** [Bubbus/ACF-Missiles#60]
It probably isnt super high priority right now, but the racks are very fragile right now. Even the smallest round from ACF will destroy a missile rack, which makes them impractical for real combat. I think that while the fragility is fair, they should stop working instead of dissapear entirely. This is pretty unrealistic and it can cause aircraft to spazz due to the sudden reduction in mass.

**Comment by Bubbus** [comment]
They've got to have a downside somewhere, but yeah maybe.  I'll take a look at the code and maybe put some minimum penetration values for detonation in there.

**Comment by Kardel420** [comment]
I agree, ACF Racks are way too weak to the smallest explosion and the weakest bullet in the game.
If i remember correctly, Missiles remain unarmed on their racks/tubes until theyre armed to be fired, to prevent warhead detonation caused by small ammounts of damages like small arms or even some explosions. Rocketpods and tubed missiles are more resistant to damage than their racked counterparts because of the extra shielding around them, even if theyre not even actually armored, the tube/pod still protects them a bit.

**Comment by Bubbus** [comment]
did the thing e1a8c79fff1865bb6af879eea82bc58fcc7a8d07
