### ISSUE TITLE
missles and parenting 

### ISSUE THREAD

**Issue by killersanta336** [Bubbus/ACF-Missiles#90]
i knkw its not possibe i looked but is there a way i could possibly att the ability to parent the missile racks/pods to a prop and still have them work. i know its possible with acf  as i fooled around with the files and told it to do so. but the main reason i wanna do this is because i have  vehicles i wanna make that need this to be possible  please help!

**Comment by Cre8or** [comment]
The racks and missiles were intentionally designed to be non-parentable, to match the behaviour of regular ACF guns (which can also not be parented). Unless ACF changes this behaviour, we are not going to change it either.

It's not that we personally don't want to, but it's more about the balancing, as you could otherwise attach hundreds of heavy guided missiles to the tiniest vehicle imaginable. Which is why ACF doesn't do it.

However, if the ACF devs decide to allow parenting guns in the future, we'll probably follow their decision. If you want this to happen, you'll have to talk to them first.
